config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  root 'quotes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  self.per_page = 12
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :redirect, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all.order("created_at DESC").paginate(page: params[:page])
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def redirect
      redirect_to root_path
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:citation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anonymous Quotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id='body'>
      <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(quote.errors.count, 'error') %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@quote, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
    <div class='form-group'>
      <div class='control-label col-sm-2'>
      <% f.label :citation %>
      </div>
      <div class='col-sm-8'>
      <%= f.text_area :citation, class: 'form-control', placeholder: 'Write your thoughts here...', autofocus: true, :required => true %>
      </div>
    </div>
    <div class='form-group'>
      <div class='col-sm-offset-2 col-sm-10'>
        <%= f.submit class: 'btn btn-primary btn-lg'%>
        <%= link_to 'Back', root_path, class: 'btn btn-warning btn-lg' %>
      </div>
    </div>
    <%end%>
  </div>
</div>

app/views/quotes/index.html.erb
<section id='heading' class='jumbotron text-center'>
  <div class='container'>
    <h1 class='jumbotron-heading'>Awesome quotes</h1>
    <p class='lead text-muted'>Submit your quotes below!</p>
    <p><%= link_to 'New Quote', new_quote_path, class:'btn btn-primary' %></p>
  </div>
</section>

<div class='container'>
  <div class='row'>
    <h1 id='notice'><%= notice %></h1>
  </div>
</div>

<br>

<% @quotes.each do |quote| %>
<div class='row'>
  <div class='col-sm-8 col-sm-offset-2'>
    <div  class='jumbotron'>
        <blockquote class='blockquote'>
          <h1>"<%= quote.citation %>"</h1>
          <footer class='blockquote-footer'>
            <%= quote.created_at.strftime('%d %B %Y') %>
          </footer>
        </blockquote>
    </div>
  </div>
</div>
<%end%>

<div class='row'>
  <div class='col-sm-4 col-sm-offset-5'>
    <%= will_paginate(@quotes) %>
  </div>
</div>

app/views/quotes/new.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>New Quote</h1>
    <br>
    <%= render 'form', quote: @quote %>
  </div>
</div>